### ISSUE TITLE
Move your main function up in your file. Only execution in the bottom

### ISSUE THREAD

**Issue by ericlee0920** [UBC-MDS/DSCI_522_group_31#53]

**Comment by lephanthuymai** [comment]
I guess this relates to the 4th script (our longest one): src/04_build_model.py

**Comment by yaz-saleh** [comment]
Group discussion notes:

- [ ] Move `main` function to the top in `01_download_data.py`, `02_cleanup_data.py`, `03_generate_eda.py`, `04_build_model.py`

- [ ] Ensure all scripts still function as intended
